/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DemandArea {
  'id' : number,
  'lat' : number,
  'lng' : number,
  'userId' : Principal,
  'demandLabel' : string,
  'timestamp' : Time,
}
export interface DemandAreaInput {
  'lat' : number,
  'lng' : number,
  'demandLabel' : string,
}
export interface RewardInfo {
  'rewardPoints' : bigint,
  'moneySaved' : number,
  'totalRides' : bigint,
}
export interface Ride {
  'id' : number,
  'status' : string,
  'dropLat' : number,
  'dropLng' : number,
  'driverId' : [] | [Principal],
  'vehicleType' : string,
  'userId' : Principal,
  'fare' : number,
  'pickupLat' : number,
  'pickupLng' : number,
  'timestamp' : Time,
  'rideType' : string,
}
export interface RideInput {
  'dropLat' : number,
  'dropLng' : number,
  'vehicleType' : string,
  'pickupLat' : number,
  'pickupLng' : number,
  'rideType' : string,
}
export type Time = bigint;
export interface User {
  'id' : Principal,
  'locationLat' : number,
  'locationLng' : number,
  'vehicleType' : string,
  'password' : string,
  'name' : string,
  'role' : string,
  'rewardPoints' : bigint,
  'moneySaved' : number,
  'phone' : string,
  'totalRides' : bigint,
}
export interface UserInput {
  'locationLat' : number,
  'locationLng' : number,
  'vehicleType' : string,
  'password' : string,
  'name' : string,
  'role' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDemandArea' : ActorMethod<[DemandAreaInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookRide' : ActorMethod<[RideInput], undefined>,
  'estimateFare' : ActorMethod<[string, string, number, bigint], number>,
  'getAllDemandAreas' : ActorMethod<[], Array<DemandArea>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRewardInfo' : ActorMethod<[Principal], RewardInfo>,
  'getRidesByUser' : ActorMethod<[Principal], Array<Ride>>,
  'getUserById' : ActorMethod<[Principal], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], User>,
  'registerUser' : ActorMethod<[UserInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[User], undefined>,
  'updateDriverLocation' : ActorMethod<[number, number], undefined>,
  'updateRideStatus' : ActorMethod<[number, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];