/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DemandAreaInput = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'demandLabel' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RideInput = IDL.Record({
  'dropLat' : IDL.Float64,
  'dropLng' : IDL.Float64,
  'vehicleType' : IDL.Text,
  'pickupLat' : IDL.Float64,
  'pickupLng' : IDL.Float64,
  'rideType' : IDL.Text,
});
export const Time = IDL.Int;
export const DemandArea = IDL.Record({
  'id' : IDL.Nat32,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'userId' : IDL.Principal,
  'demandLabel' : IDL.Text,
  'timestamp' : Time,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'locationLat' : IDL.Float64,
  'locationLng' : IDL.Float64,
  'vehicleType' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'rewardPoints' : IDL.Nat,
  'moneySaved' : IDL.Float64,
  'phone' : IDL.Text,
  'totalRides' : IDL.Nat,
});
export const RewardInfo = IDL.Record({
  'rewardPoints' : IDL.Nat,
  'moneySaved' : IDL.Float64,
  'totalRides' : IDL.Nat,
});
export const Ride = IDL.Record({
  'id' : IDL.Nat32,
  'status' : IDL.Text,
  'dropLat' : IDL.Float64,
  'dropLng' : IDL.Float64,
  'driverId' : IDL.Opt(IDL.Principal),
  'vehicleType' : IDL.Text,
  'userId' : IDL.Principal,
  'fare' : IDL.Float64,
  'pickupLat' : IDL.Float64,
  'pickupLng' : IDL.Float64,
  'timestamp' : Time,
  'rideType' : IDL.Text,
});
export const UserInput = IDL.Record({
  'locationLat' : IDL.Float64,
  'locationLng' : IDL.Float64,
  'vehicleType' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDemandArea' : IDL.Func([DemandAreaInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookRide' : IDL.Func([RideInput], [], []),
  'estimateFare' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Float64],
      ['query'],
    ),
  'getAllDemandAreas' : IDL.Func([], [IDL.Vec(DemandArea)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRewardInfo' : IDL.Func([IDL.Principal], [RewardInfo], ['query']),
  'getRidesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Ride)], ['query']),
  'getUserById' : IDL.Func([IDL.Principal], [User], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'registerUser' : IDL.Func([UserInput], [], []),
  'saveCallerUserProfile' : IDL.Func([User], [], []),
  'updateDriverLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'updateRideStatus' : IDL.Func([IDL.Nat32, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DemandAreaInput = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'demandLabel' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RideInput = IDL.Record({
    'dropLat' : IDL.Float64,
    'dropLng' : IDL.Float64,
    'vehicleType' : IDL.Text,
    'pickupLat' : IDL.Float64,
    'pickupLng' : IDL.Float64,
    'rideType' : IDL.Text,
  });
  const Time = IDL.Int;
  const DemandArea = IDL.Record({
    'id' : IDL.Nat32,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'userId' : IDL.Principal,
    'demandLabel' : IDL.Text,
    'timestamp' : Time,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'vehicleType' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'rewardPoints' : IDL.Nat,
    'moneySaved' : IDL.Float64,
    'phone' : IDL.Text,
    'totalRides' : IDL.Nat,
  });
  const RewardInfo = IDL.Record({
    'rewardPoints' : IDL.Nat,
    'moneySaved' : IDL.Float64,
    'totalRides' : IDL.Nat,
  });
  const Ride = IDL.Record({
    'id' : IDL.Nat32,
    'status' : IDL.Text,
    'dropLat' : IDL.Float64,
    'dropLng' : IDL.Float64,
    'driverId' : IDL.Opt(IDL.Principal),
    'vehicleType' : IDL.Text,
    'userId' : IDL.Principal,
    'fare' : IDL.Float64,
    'pickupLat' : IDL.Float64,
    'pickupLng' : IDL.Float64,
    'timestamp' : Time,
    'rideType' : IDL.Text,
  });
  const UserInput = IDL.Record({
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'vehicleType' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDemandArea' : IDL.Func([DemandAreaInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookRide' : IDL.Func([RideInput], [], []),
    'estimateFare' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Float64],
        ['query'],
      ),
    'getAllDemandAreas' : IDL.Func([], [IDL.Vec(DemandArea)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRewardInfo' : IDL.Func([IDL.Principal], [RewardInfo], ['query']),
    'getRidesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Ride)], ['query']),
    'getUserById' : IDL.Func([IDL.Principal], [User], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'registerUser' : IDL.Func([UserInput], [], []),
    'saveCallerUserProfile' : IDL.Func([User], [], []),
    'updateDriverLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'updateRideStatus' : IDL.Func([IDL.Nat32, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };